# Rename this file to `config.yml`

modems:
  - host: 192.168.0.1
    password: "<password>"  # fill this in

probes:
  # Google
  # https://developers.google.com/speed/public-dns
  - host: "8.8.8.8"
    type: icmp-ping
  - host: "8.8.8.8"
    type: tcp-ping
    port: 53

  # Cloudflare
  # https://www.cloudflare.com/learning/dns/what-is-1.1.1.1/
  - host: "1.1.1.1"
    type: icmp-ping
  - host: "1.1.1.1"
    type: tcp-ping
    port: 53

  # OpenDNS by Cisco
  # https://www.opendns.com/
  - host: "208.67.222.222"
    type: icmp-ping
  - host: "208.67.222.222"
    type: tcp-ping
    port: 53

  # Level3 DNS
  - host: "4.2.2.1"
    type: icmp-ping
  - host: "4.2.2.1"
    type: tcp-ping
    port: 53

  # Comodo Secure DNS
  - host: "8.26.56.26"
    type: icmp-ping
  - host: "8.26.56.26"
    type: tcp-ping
    port: 53

  # Suddenlink
  # They don't seem to like ICMP
  # - host: "24.48.160.2"
  #   type: icmp-ping
  - host: "24.48.160.2"
    type: tcp-ping
    port: 53

  - host: "24.48.160.3"
    type: tcp-ping
    port: 53

ip:
# intentionally blank
