# Rename this file to `config.yml`

# fetch modem stats
arris_s33_modem:
  host: '192.168.0.1'
  password: "<password>"  # fill this in

# fetch the current host's IP
ip:

pings:
  # https://developers.google.com/speed/public-dns
  - name: "Google"
    host: "8.8.8.8"
    types:
      - icmp
      - dns-udp
      - dns-tcp

  # https://www.cloudflare.com/learning/dns/what-is-1.1.1.1/
  - name: "Cloudflare"
    host: "1.1.1.1"
    types:
      - icmp
      - dns-udp
      - dns-tcp

  # https://www.opendns.com/
  - name: "OpenDNS"
    host: "208.67.222.222"
    types:
      - icmp
      - dns-udp
      - dns-tcp

  # https://help.comodo.com/topic-72-1-766-9103-.html
  - name: "Comodo"
    host: "8.26.56.26"
    types:
      - icmp
      - dns-udp
      - dns-tcp

  # Suddenlink 1
  - name: "Suddenlink"
    host: "24.48.160.2"
    types:
      - icmp
      - dns-udp
      - dns-tcp

  # Suddenlink 2
  - name: "Suddenlink"
    host: "24.48.160.3"
    types:
      - icmp
      - dns-udp
      - dns-tcp
