version: "3.9"

services:

  ispee:
    container_name: ispee
    restart: unless-stopped
    build:
      context: .
    image: ispee
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./config.yml
        target: /etc/ispee/config.yml
        read_only: true
    networks:
      - ispee-network

  vmagent:
    container_name: ispee-vmagent
    restart: unless-stopped
    image: victoriametrics/vmagent
    ports:
      - target: 8429
        published: 8429
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./victoriametrics/config/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
      - type: volume
        source: vmagent-storage
        target: /vmagentdata
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
    depends_on:
      - victoriametrics
    networks:
      - ispee-network

  victoriametrics:
    container_name: ispee-victoriametrics
    restart: unless-stopped
    image: victoriametrics/victoria-metrics
    ports:
      - target: 8428
        published: 8428
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: victoriametrics-storage
        target: /storage
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
      - "--retentionPeriod=1"
    networks:
      - ispee-network

  grafana:
    container_name: ispee-grafana
    restart: unless-stopped
    image: grafana/grafana
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    depends_on:
      - victoriametrics
    volumes:
      - type: bind
        source: ./grafana/config/grafana.ini
        target: /etc/grafana/grafana.ini
        read_only: true
      - type: bind
        source: ./grafana/provisioning/
        target: /etc/grafana/provisioning
      - type: bind
        source: ./grafana/dashboards/
        target: /etc/dashboards
        read_only: true
      - type: volume
        source: grafana-storage
        target: /var/lib/grafana
    networks:
      - ispee-network

volumes:
  grafana-storage:
    name: ispee-grafana-storage
  victoriametrics-storage:
    name: ispee-victoriametrics-storage
  vmagent-storage:
    name: ispee-vmagent-storage

networks:
  ispee-network:
    name: ispee-network
