# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.10-slim-buster

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# rich's log output defaults to super small 80 otherwise
ENV COLUMNS=200

# vscode can't debug the threads right, so use sequential logic instead
ENV PROBER_USE_THREADS=false

# expose prometheus http endpoint
EXPOSE 8000/tcp

WORKDIR /app

COPY pyproject.toml /app/
RUN set -ex \
    && mkdir /app/prober \
    && touch /app/prober/__init__.py \
    && pip install /app

COPY prober/ /app/prober/
COPY config.yml /etc/prober/config.yml

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
# RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
# USER appuser

# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
CMD ["python", "-m", "prober"]
