{
 "title": "Latency",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "type",
    "label": "Probe Type",
    "query": "udp-dns-ping,tcp-dns-ping,icmp-ping"
   },
   {
    "name": "minstep",
    "label": "Minimum Interval",
    "query": "15s,30s,1m,5m,15m,30m,1h,2h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Average Latency",
   "type": "stat",
   "description": "Average of last recorded durations for each host.\n\n\nNote: if an absolute time range is selected, this panel reflects the end of that range.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(ping_duration_seconds_sum{type=\"$type\"}[$__interval]))/avg(rate(ping_duration_seconds_count{type=\"$type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Current Failure Rate",
   "type": "stat",
   "description": "The percentage of probes that failed in the last reading. This could be because of timeout, packet loss, routing failures, invalid packets, etc.\n\nNote: if an absolute time range is selected, this panel reflects the end of that range.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ping_failure_total{type=\"$type\"}[$__interval]))/sum(increase(ping_total{type=\"$type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Historical Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "The yellow line (50ms) and red line (100ms) arbitrarily delineate regions of \"good\", \"okay\", and \"bad\".",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ping_duration_seconds_sum{type=\"$type\"}[$__interval])/rate(ping_duration_seconds_count{type=\"$type\"}[$__interval])",
     "legendFormat": "{{destination}}"
    },
    {
     "expr": "avg(rate(ping_duration_seconds_sum{type=\"$type\"}[$__interval])/rate(ping_duration_seconds_count{type=\"$type\"}[$__interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Latency Percentiles Over Range",
   "type": "stat",
   "description": "The \"nth percentile is x\" tells you that n/100 percent of the traffic is at or below x. For example, if the 90th percentile is 50ms, then 90% of the traffic is <= 50ms, while the other 10% is > 50ms.\n\nViewing a set of percentiles can illuminate the variance of the underlying measurements.\n\nNote that the the values of the percentiles are typically interpolations instead of actually-recorded values.",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantiles(\"phi\", 0.5, 0.9, 0.95, 0.99, sum(rate(ping_duration_seconds_bucket{type=\"$type\"}[$__range])) by (le))",
     "legendFormat": "{{phi}} Percentile"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(ping_failure_total{type=\"$type\"}[$__interval])",
     "legendFormat": "{{destination}}"
    },
    {
     "expr": "sum(increase(ping_failure_total{type=\"$type\"}[$__interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Failure Rate Over Range",
   "type": "stat",
   "description": "The number of failures divided by the number of readings for all probes in the current range.",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ping_failure_total{type=\"$type\"}[$__range]))/sum(increase(ping_total{type=\"$type\"}[$__range]))"
    }
   ]
  }
 ]
}