{
 "title": "Modem Info",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "minstep",
    "label": "Minimum Interval",
    "query": "15s,30s,1m,5m,15m,30m,1h,2h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Corrected Codewords Over Range",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(corrected_codewords_total[$__range]))",
     "legendFormat": "{{frequency_megahertz}} MHz"
    }
   ]
  },
  {
   "title": "Total Uncorrectable Codewords Over Range",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(uncorrectable_codewords_total[$__range]))",
     "legendFormat": "{{frequency_megahertz}} MHz"
    }
   ]
  },
  {
   "title": "Corrected Codewords",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(increase(corrected_codewords_total[$__interval]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Uncorrectable Codewords",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum(increase(uncorrectable_codewords_total[$__interval]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Corrected Codewords",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(corrected_codewords_total[$__interval])",
     "legendFormat": "{{frequency_megahertz}} MHz"
    }
   ]
  },
  {
   "title": "Uncorrectable Codewords",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "increase(uncorrectable_codewords_total[$__interval])",
     "legendFormat": "{{frequency_megahertz}} MHz"
    }
   ]
  },
  {
   "title": "Signal to Noise Ratio",
   "type": "state-timeline",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    { "expr": "snr_db[$__interval]", "legendFormat": "{{frequency_megahertz}} MHz" }
   ]
  },
  {
   "title": "Power (Absolute Value)",
   "type": "state-timeline",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    { "expr": "abs(power_dbmv[$__interval])", "legendFormat": "{{frequency_megahertz}} MHz" }
   ]
  }
 ]
}