#/bin/sh

# this file will be run on the victoriametrics/vmrestore image
# see the "export-metrics" makefile target for usage
#   - note the metrics data mount at /storage
#   - note the host mount at /host
#   - note we're in the conn-probe-network network, so we can access the victoriametrics HTTP snapshot API

# note that the victoria metrics server must be stopped for vmrestore to work.

# the out-of-the-box behavior is vmrestore is to load a directory structure that was generated by vmbackup.
# but, we've augmented the backup process to additionally produce a tar archive (as seen in backup-metrics.sh)
# therefore, we first extract, then run vmrestore

tar -xzvf "/host/metrics.tar.gz" -C "/"

/./vmrestore-prod \
    -storageDataPath "/storage" \
    -src "fs:///backup"
